name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: github-metrics.svg
          
          # 3D Календарь
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Языки
          plugin_languages: yes
          plugin_languages_sections: most-used
          
          # НАСТРОЙКИ ТЕМЫ
          config_timezone: Europe/Moscow
          template: classic
          base_indepth: yes
          
          # Включаем темную тему через встроенный параметр
          config_padding: 0, 5
          config_display: large
          
          # Вместо config_colors используем эти параметры для языков и общего стиля:
          plugin_languages_colors: "github" # Использует стандартные цвета языков
          
          # Добавляем CSS, чтобы принудительно закрасить фон в черный
          extras_css: |
            h2, h3 { color: #f3e600; } 
            section { background-color: #000000; }
            svg { background-color: #000000; }
